:agents:
  :recogito:
    :uri_match: "http://pelagios.org/recogito#version1.0"
    :transformations:
      :OACIdentifier: "/data/xslt/oac/recogito_to_oac.xsl"
  :eagle:
    :uri_match: "http://www.eagle-network.eu/wiki"
    :transformations:
      :CTSIdentifier: "/data/xslt/eagle-xml-perseids.xsl"
    :collections:
      :CTSIdentifier: "eagle"
