lib/rxsugar:
  :type: git
  :repository: git://github.com/papyri/xsugar.git
  :revision: rails-3-nfd

data/xslt/epidoc:
  :type: git
  :repository: https://github.com/DCLP/epidoc-xslt.git
  :revision: b28313ab37642f7e9ed8bba69d305c4c85824690

data/xslt/pn/navigator:
  :type: git
  :repository: git://github.com/DCLP/navigator.git
  :revision: 7661cda98c35b5472b499b5abdfb6055a28a31c3
