vendor/plugins/rxsugar:
  :type: git
  :repository: git://halsted.vis.uky.edu/git/xsugar.git
  :revision: 3f6e0b5bcf69bf3b67b20a97b86823eba9b879fb

# vendor/plugins/render_component:
#   :type: git
#   :repository: git://github.com/lackac/render_component.git
#   :revision: rails-edge
  
data/xslt/epidoc:
  :type: subversion
  :repository: https://epidoc.svn.sourceforge.net/svnroot/epidoc/trunk/example-p5-xslt/
  :revision: 1138