vendor/plugins/rxsugar:
  :type: git
  :repository: git://halsted.vis.uky.edu/git/xsugar.git
  :revision: 65cad7bf0537d10956b40685a465c9ffce472d08

data/xslt/epidoc:
  :type: subversion
  :repository: https://epidoc.svn.sourceforge.net/svnroot/epidoc/trunk/example-p5-xslt/
  :revision: 1150
