vendor/plugins/rxsugar:
  :type: git
  :repository: git://github.com/papyri/xsugar.git
  :revision: 80ec3c9fc14fc82aaee3483786f064dc3dd6dd86

data/xslt/epidoc:
  :type: subversion
  :repository: https://epidoc.svn.sourceforge.net/svnroot/epidoc/trunk/example-p5-xslt
  :revision: 1755 

data/xslt/pn/navigator:
  :type: git
  :repository: git://github.com/papyri/navigator.git
  :revision: c03dd1a2a21ca2cfe72eb0b2cc4306a02db5b4fa
