vendor/plugins/rxsugar:
  :type: git
  :repository: git://github.com/papyri/xsugar.git
  :revision: 485499072b15d92498617659c49c80812d869edf

data/xslt/epidoc:
  :type: subversion
  :repository: https://epidoc.svn.sourceforge.net/svnroot/epidoc/tags/IDP-August-release-2/example-p5-xslt/
  :revision: HEAD
