vendor/plugins/rxsugar:
  :type: git
  :repository: git://halsted.vis.uky.edu/git/xsugar.git
  :revision: 649f2a6f8d2ec9ba0143e8f197a62b7ae255d644

data/xslt/epidoc:
  :type: subversion
  :repository: https://epidoc.svn.sourceforge.net/svnroot/epidoc/tags/r-8-9/example-p5-xslt/
  :revision: HEAD
