lib/rxsugar:
  :type: git
  :repository: git://github.com/papyri/xsugar.git
  :revision: rails-3-nfd

data/xslt/epidoc:
  :type: git
  :repository: https://github.com/DCLP/epidoc-xslt.git
  :revision: 382b55ce781c885f8b33fbadadcc3528dfcb1545

data/xslt/pn/navigator:
  :type: git
  :repository: git://github.com/DCLP/navigator.git
  :revision: 47f10946b633f1e253fb2bfc9ba109463d580aae
