vendor/plugins/rxsugar:
  :type: git
  :repository: git://halsted.vis.uky.edu/git/xsugar.git
  :revision: c7ed6f8221eb79c413552bff8c01977c3993d1f4

data/xslt/epidoc:
  :type: subversion
  :repository: https://epidoc.svn.sourceforge.net/svnroot/epidoc/tags/r-8-7bis/example-p5-xslt/
  :revision: 1391
