vendor/plugins/rxsugar:
  :type: git
  :repository: git://halsted.vis.uky.edu/git/xsugar.git
  :revision: 5288cb09e1c8b7a99cd0d6f0ecc3a73fe0019d3e

data/xslt/epidoc:
  :type: subversion
  :repository: https://epidoc.svn.sourceforge.net/svnroot/epidoc/tags/r-8-9/example-p5-xslt/
  :revision: HEAD
