lib/rxsugar:
  :type: git
  :repository: git://github.com/papyri/xsugar.git
  :revision: rails-3-nfd

data/xslt/epidoc:
  :type: git
  :repository: https://github.com/DCLP/epidoc-xslt.git
  :revision: 4e7ee2fcfd35f9d2667fa3af43d5cca141660929

data/xslt/pn/navigator:
  :type: git
  :repository: git://github.com/DCLP/navigator.git
  :revision: 84e543b2390d23a215fc309c615369bd250a91b0
