vendor/plugins/rxsugar:
  :type: git
  :repository: git://halsted.vis.uky.edu/git/xsugar.git
  :revision: a80d3c21913e42197945df7f40e498e22d353934

data/xslt/epidoc:
  :type: subversion
  :repository: https://epidoc.svn.sourceforge.net/svnroot/epidoc/tags/r-8-7/example-p5-xslt/
  :revision: 1384
