vendor/plugins/rxsugar:
  :type: git
  :repository: git://github.com/papyri/xsugar.git
  :revision: master

data/xslt/epidoc:
  :type: subversion
  :repository: https://epidoc.svn.sourceforge.net/svnroot/epidoc/trunk/example-p5-xslt/
  :revision: HEAD

data/xslt/pn/navigator:
  :type: git
  :repository: git://github.com/papyri/navigator.git
  :revision: master
