vendor/plugins/rxsugar:
  :type: git
  :repository: git://github.com/papyri/xsugar.git
  :revision: aeb17cc8bd4abe5d69fd4eb0f541326fd5172ddf

data/xslt/epidoc:
  :type: subversion
  :repository: https://epidoc.svn.sourceforge.net/svnroot/epidoc/tags/IDP-August-release/example-p5-xslt/
  :revision: HEAD
