vendor/plugins/rxsugar:
  :type: git
  :repository: git://halsted.vis.uky.edu/git/xsugar.git
  :revision: 2b4db9f939d51b01544b01b2684b573ca8bcae35

data/xslt/epidoc:
  :type: subversion
  :repository: https://epidoc.svn.sourceforge.net/svnroot/epidoc/tags/r-8-7bis/example-p5-xslt/
  :revision: 1391
