vendor/plugins/rxsugar:
  :type: git
  :repository: git://github.com/papyri/xsugar.git
  :revision: a867ab0da3374ad87d9ae904cf57c24fceef50e8

data/xslt/epidoc:
  :type: subversion
  :repository: https://epidoc.svn.sourceforge.net/svnroot/epidoc/tags/IDP-Nov-release-2/example-p5-xslt
  :revision: HEAD
