vendor/plugins/rxsugar:
  :type: git
  :repository: git://halsted.vis.uky.edu/git/xsugar.git
  :revision: a53eb58ab6a192460fc5548f030964fe9d054c75

# vendor/plugins/render_component:
#   :type: git
#   :repository: git://github.com/lackac/render_component.git
#   :revision: rails-edge
  
data/xslt/epidoc:
  :type: subversion
  :repository: https://epidoc.svn.sourceforge.net/svnroot/epidoc/trunk/example-p5-xslt/
  :revision: 1146
