# attributes for elements
#
# :xpath (mandatory)
# :multiple -> true | false (optional, defaults to false)
# :optional -> true | false (optional, defaults to true)
# :default -> default value as string, multiple entries reasonable do not support default values (optional)
# :pattern -> ruby style regular expression /\A0(\.\d)?|1\Z/ (optional)
# :children -> recursive element structure
#
# attributes for attributes
#
# :name (mandatory) 
# :optional (same as above)
# :default (same as above)
# :pattern (same as above)

:hgv:
  :metadata:
    :titleStmt:
      :xpath: /TEI/teiHeader/fileDesc/titleStmt/title
    :publicationTitle:
      :xpath: /TEI/text/body/div[@type='bibliography'][@subtype='principalEdition']/listBibl/bibl[@type='publication'][@subtype='principal']/title[@level='s'][@type='abbreviated']
    :publicationVolume:
      :xpath: /TEI/text/body/div[@type='bibliography'][@subtype='principalEdition']/listBibl/bibl[@type='publication'][@subtype='principal']/biblScope[@type='volume']
    :publicationNumbers:
      :xpath: /TEI/text/body/div[@type='bibliography'][@subtype='principalEdition']/listBibl/bibl[@type='publication'][@subtype='principal']/biblScope[@type='numbers']
    :publicationFascicle:
      :xpath: /TEI/text/body/div[@type='bibliography'][@subtype='principalEdition']/listBibl/bibl[@type='publication'][@subtype='principal']/biblScope[@type='fascicle']
    :publicationSide:
      :xpath: /TEI/text/body/div[@type='bibliography'][@subtype='principalEdition']/listBibl/bibl[@type='publication'][@subtype='principal']/biblScope[@type='side']
    :publicationLine:
      :xpath: /TEI/text/body/div[@type='bibliography'][@subtype='principalEdition']/listBibl/bibl[@type='publication'][@subtype='principal']/biblScope[@type='lines']
    :publicationPages:
      :xpath: /TEI/text/body/div[@type='bibliography'][@subtype='principalEdition']/listBibl/bibl[@type='publication'][@subtype='principal']/biblScope[@type='pages']
    :publicationParts:
      :xpath: /TEI/text/body/div[@type='bibliography'][@subtype='principalEdition']/listBibl/bibl[@type='publication'][@subtype='principal']/biblScope[@type='parts']
    :collectionPlaceName:
      :xpath: /TEI/teiHeader/fileDesc/sourceDesc/msDesc/msIdentifier/placeName/settlement
    :collection:
      :xpath: /TEI/teiHeader/fileDesc/sourceDesc/msDesc/msIdentifier/collection
    :collectionInventoryNumber:
      :xpath: /TEI/teiHeader/fileDesc/sourceDesc/msDesc/msIdentifier/idno[@type='invNo']
    :collectionTemporaryNotes:
      :xpath: /TEI/teiHeader/fileDesc/sourceDesc/msDesc/msIdentifier/altIdentifier[@type='temporary']/note
    :collectionTemporaryInventoryNumber:
      :xpath: /TEI/teiHeader/fileDesc/sourceDesc/msDesc/msIdentifier/altIdentifier[@type='temporary']/idno[@type='invNo']
    :tmNo:
      :xpath: /TEI/teiHeader/fileDesc/publicationStmt/idno[@type='TM']
      :pattern: /\A\d+\Z/
    :illustrations:
      :xpath: /TEI/text/body/div[@type='bibliography'][@subtype='illustrations']/p/bibl[@type='illustration']
      :multiple: true
    :contentText:
      :xpath: /TEI/teiHeader/profileDesc/textClass/keywords[@scheme='hgv']/term
      :multiple: true
    :otherPublications:
      :xpath: /TEI/text/body/div[@type='bibliography'][@subtype='otherPublications']/listBibl/bibl[@type='publication'][@subtype='other']
      :multiple: true
    :translationsDe: #tweaked but may need more added to form - may have multiples
      :xpath: /TEI/text/body/div[@type='bibliography'][@subtype='translations']/listBibl[@xml:lang='de']/bibl[@type='translations']
      :multiple: true
    :translationsEn:
      :xpath: /TEI/text/body/div[@type='bibliography'][@subtype='translations']/listBibl[@xml:lang='en']/bibl[@type='translations']
      :multiple: true
    :translationsIt:
      :xpath: /TEI/text/body/div[@type='bibliography'][@subtype='translations']/listBibl[@xml:lang='it']/bibl[@type='translations']
      :multiple: true
    :translationsEs:
      :xpath: /TEI/text/body/div[@type='bibliography'][@subtype='translations']/listBibl[@xml:lang='es']/bibl[@type='translations']
      :multiple: true
    :translationsLa:
      :xpath: /TEI/text/body/div[@type='bibliography'][@subtype='translations']/listBibl[@xml:lang='la']/bibl[@type='translations']
      :multiple: true
    :translationsFr:
      :xpath: /TEI/text/body/div[@type='bibliography'][@subtype='translations']/listBibl[@xml:lang='fr']/bibl[@type='translations']
      :multiple: true
    :bl: #works same but may need more added to form
      :xpath: /TEI/text/body/div[@type='bibliography'][@subtype='corrections']/listBibl/bibl[@type='BL']
      :multiple: true
      :children:
        :volume:
          :xpath: biblScope[@type='volume']
          :optional: false
        :page:
          :xpath: biblScope[@type='pages']
          :optional: false
    :notes:
      :xpath: /TEI/text/body/div[@type='commentary'][@subtype='general']/p
    :material:
      :xpath: /TEI/teiHeader/fileDesc/sourceDesc/msDesc/physDesc/objectDesc/supportDesc/support/material
    :provenanceAncientFindspot:
      :xpath: /TEI/teiHeader/fileDesc/sourceDesc/msDesc/history/origin/p/placeName[@type='ancientFindspot']
    :provenanceNome:
      :xpath: /TEI/teiHeader/fileDesc/sourceDesc/msDesc/history/origin/p/geogName[@type='nome']
    :provenanceAncientRegion:
      :xpath: /TEI/teiHeader/fileDesc/sourceDesc/msDesc/history/origin/p/geogName[@type='ancientRegion']
    :provenanceModernFindspot: #guessed at this one
      :xpath: /TEI/teiHeader/fileDesc/sourceDesc/msDesc/history/origin/p/geogName[@type='modernFindspot']
    :plannedForFuturePrintRelease: #does not currently exist in data
      :xpath: /TEI/teiHeader/fileDesc/publicationStmt/idno[@type='futurePrintRelease']
      :pattern: /\A.+?;.+?;.*\Z/
    :mentionedDate:
      :xpath: /TEI/text/body/div[@type='commentary'][@subtype='mentionedDates']/list/item
      :multiple: true
      :children:
        :ref:
          :xpath: ref
        :note:
          :xpath: note
        :date:
          :xpath: date[@type='mentioned']
          :attributes:
            :when:
              :name: when
            :from:
              :name: from
            :to:
              :name: to
          :children:
            :certainty:
              :xpath: certainty[@locus='value']
              :multiple: true
              :attributes:
                :target:
                  :name: target
                :relation:
                  :name: given
                  :pattern: /\A#dateAlternative[XYZ]\Z/
                :degree:
                  :name: degree
                  :optional: false
                  :pattern: /\A0(\.\d)?|1\Z/
    #:mentionedDateOriginal:
    #  :xpath: /TEI/text/body/div[@type='commentary'][@subtype='mentionedDates']/note[@type='original']
    #:mentionedDateSource:
    #  :xpath: /TEI/text/body/div[@type='commentary'][@subtype='mentionedDates']/note[@type='source']
    #  :pattern: /\AHGV\.fp7|MentionedDates\.fp7\Z/
    :textDate:
      :xpath: /TEI/teiHeader/fileDesc/sourceDesc/msDesc/history/origin/origDate[@type='textDate']
      :multiple: true
      :pattern: /\A-?\d\d\d\d(-\d\d(-\d\d)?)?\Z/
      :attributes:
        :textDateId:
          :name: xml:id
          :default: "dateAlternativeX"
          :pattern: /\AdateAlternative[XYZ]\Z/
        :textDateWhen:
          :name: when
          :pattern: /\A-?\d\d\d\d(-\d\d(-\d\d)?)?\Z/
        :textDateFrom:
          :name: notBefore
          :pattern: /\A-?\d\d\d\d(-\d\d(-\d\d)?)?\Z/
        :textDateTo:
          :name: notAfter
          :pattern: /\A-?\d\d\d\d(-\d\d(-\d\d)?)?\Z/
      :children:
        :onDate:
          :xpath: date[@type='on']
          :attributes:
            :certainty:
              :name: cert
              :pattern: /\A0(\.\d)?|1\Z/
          :children:
            :offset:
              :xpath: offset
              :pattern: /\Abefore|after\Z/
            :century:
              :xpath: date[@type='century']
              :pattern: /\A\d{{1,2}}\Z/
              :attributes:
                :extent:
                  :name: extent
                  :pattern: /\Abeginning|middle|end\Z/
            :year:
              :xpath: date[@type='year']
              :pattern: /\A\d{{1,4}}\Z/
              :attributes:
                :extent:
                  :name: extent
                  :pattern: /\Abeginning|middle|end\Z/
                :certainty:
                  :name: cert
                  :pattern: /\A0(\.\d)?|1\Z/
            :month:
              :xpath: date[@type='month']
              :pattern: /\A\d{{1,2}}\Z/
              :attributes:
                :extent:
                  :name: extent
                  :pattern: /\Abeginning|middle|end\Z/
                :certainty:
                  :name: cert
                  :pattern: /\A0(\.\d)?|1\Z/
            :day:
              :xpath: date[@type='day']
              :pattern: /\A\d{{1,2}}\Z/
              :attributes:
                :certainty:
                  :name: cert
                  :pattern: /\A0(\.\d)?|1\Z/
        :fromDate:
          :xpath: date[@type='from']
          :attributes:
            :certainty:
              :name: cert
              :pattern: /\A0(\.\d)?|1\Z/
          :children:
            :offset:
              :xpath: offset
              :pattern: /\Abefore|after\Z/
            :century:
              :xpath: date[@type='century']
              :pattern: /\A\d{{1,2}}\Z/
              :attributes:
                :extent:
                  :name: extent
                  :pattern: /\Abeginning|middle|end\Z/
            :year:
              :xpath: date[@type='year']
              :pattern: /\A\d{{1,4}}\Z/
              :attributes:
                :extent:
                  :name: extent
                  :pattern: /\Abeginning|middle|end\Z/
                :certainty:
                  :name: cert
                  :pattern: /\A0(\.\d)?|1\Z/
            :month:
              :xpath: date[@type='month']
              :pattern: /\A\d{{1,2}}\Z/
              :attributes:
                :extent:
                  :name: extent
                  :pattern: /\Abeginning|middle|end\Z/
                :certainty:
                  :name: cert
                  :pattern: /\A0(\.\d)?|1\Z/
            :day:
              :xpath: date[@type='day']
              :pattern: /\A\d{{1,2}}\Z/
              :attributes:
                :certainty:
                  :name: cert
                  :pattern: /\A0(\.\d)?|1\Z/
        :toDate:
          :xpath: date[@type='to']
          :attributes:
            :certainty:
              :name: cert
              :pattern: /\A0(\.\d)?|1\Z/
          :children:
            :offset:
              :xpath: offset
              :pattern: /\Abefore|after\Z/
            :century:
              :xpath: date[@type='century']
              :pattern: /\A\d{{1,2}}\Z/
              :attributes:
                :extent:
                  :name: extent
                  :pattern: /\Abeginning|middle|end\Z/
            :year:
              :xpath: date[@type='year']
              :pattern: /\A\d{{1,4}}\Z/
              :attributes:
                :extent:
                  :name: extent
                  :pattern: /\Abeginning|middle|end\Z/
                :certainty:
                  :name: cert
                  :pattern: /\A0(\.\d)?|1\Z/
            :month:
              :xpath: date[@type='month']
              :pattern: /\A\d{{1,2}}\Z/
              :attributes:
                :extent:
                  :name: extent
                  :pattern: /\Abeginning|middle|end\Z/
                :certainty:
                  :name: cert
                  :pattern: /\A0(\.\d)?|1\Z/
            :day:
              :xpath: date[@type='day']
              :pattern: /\A\d{{1,2}}\Z/
              :attributes:
                :certainty:
                  :name: cert
                  :pattern: /\A0(\.\d)?|1\Z/