development:
  treebank_editor:
    :edit_url: "http://localhost/exist/rest/db/app/treebank-editsentence-perseids-test.xhtml?doc=DOC&s=SENT&numSentences=MAX"
    :view_url: "http://localhost/exist/rest/db/app/treebank-editsentence-perseids-test.xhtml?doc=DOC&s=SENT&numSentences=MAX&app=viewer"
  alignment_editor:
    :edit_url: "http://localhost/exist/rest/db/app/align-editsentence-perseids-test.xhtml?doc=DOC&s=SENT&numSentences=MAX"
    :view_url: "http://localhost/exist/rest/db/app/align-editsentence-perseids-test.xhtml?doc=DOC&s=SENT&numSentences=MAX&app=viewer"
  cite_image_service:
    :context_url: "http://services.perseus.tufts.edu/sparqlimg/api?request=GetIIPMooViewer&urn="
    :binary_url:  "http://services.perseus.tufts.edu/sparqlimg/api?request=GetBinaryImage&urn="
  cts_tokenizer:
    :default:
      :request_url: "http://localhost/exist/rest/db/xq/tokenize.xquery?splitting=false&uri="
    :lat:
      :request_url: "http://localhost/llt/tokenize?xml=true&merging=false&splitting=false&uri="
    
    
test:
  treebank_editor:
    :edit_url: "http://localhost/exist/rest/db/app/treebank-editsentence-perseids.xhtml?doc=DOC&s=SENT&numSentences=MAX"
    :view_url: "http://localhost/exist/rest/db/app/treebank-editsentence-perseids.xhtml?doc=DOC&s=SENT&numSentences=MAX&app=viewer"
  alignment_editor:
    :edit_url: "http://localhost/exist/rest/db/app/align-editsentence-perseids-test.xhtml?doc=DOC&s=SENT&numSentences=MAX"
    :view_url: "http://localhost/exist/rest/db/app/align-editsentence-perseids-test.xhtml?doc=DOC&s=SENT&numSentences=MAX&app=viewer"
  cite_image_service:
    :context_url: "http://services.perseus.tufts.edu/sparqlimg/api?request=GetIIPMooViewer&urn="
    :binary_url:  "http://services.perseus.tufts.edu/sparqlimg/api?request=GetBinaryImage&urn="
  cts_tokenizer:
    :default:
      :request_url: "http://sosol.perseids.org/exist/rest/db/xq/tokenize.xquery?merging=false&splitting=false&uri="
    :lat:
      :request_url: "http://services.perseids.org/llt/tokenize?xml=true&merging=false&splitting=false&uri="
   
    
production:
  treebank_editor:
    :edit_url: "http://sosol.perseids.org/alpheios/app/treebank-editsentence-perseids.xhtml?doc=DOC&s=SENT&numSentences=MAX"
    :view_url: "http://sosol.perseids.org/alpheios/app/treebank-editsentence-perseids.xhtml?doc=DOC&s=SENT&numSentences=MAX&app=viewer"
  alignment_editor:
    :edit_url: "http://sosol.perseids.org/alpheios/app/align-editsentence-perseids-test.xhtml?doc=DOC&s=SENT&numSentences=MAX"
    :view_url: "http://sosol.perseids.org/alpheios/app/align-editsentence-perseids-test.xhtml?doc=DOC&s=SENT&numSentences=MAX&app=viewer"
  cite_image_service:
    :context_url: "http://services.perseus.tufts.edu/sparqlimg/api?request=GetIIPMooViewer&urn="
    :binary_url:  "http://services.perseus.tufts.edu/sparqlimg/api?request=GetBinaryImage&urn="
  cts_tokenizer:
    :default:
      :request_url: "http://localhost/exist/rest/db/xq/tokenize.xquery?merging=false&splitting=false&uri="
    :lat:
      :request_url: "http://services.perseids.org/llt/tokenize?xml=true&merging=false&splitting=false&uri="
    
