development:
  treebank_editor:
    alpheios:
      :text: 'Alpheios'
      :method: 'get'
      :uri: 'http://github.com/alpheios-project/treebank-editor'
      :actions:
        :edit:
          :href: "http://localhost/exist/rest/db/app/treebank-editsentence-perseids-test.xhtml?s=SENT&numSentences=MAX"
          :id_param: 'doc'
          :text: 'Edit in Alpheios'
        :view:
          :href: "http://localhost/exist/rest/db/app/treebank-editsentence-perseids-test.xhtml?s=SENT&numSentences=MAX&app=viewer"
          :id_param: 'doc'
          :text: 'Preview in Alpheios'
        :create:
          :href: "http://localhost/exist/rest/db/app/treebank-entertext-perseids-test.xhtml?"
          :text: 'via Alpheios'
          :id_param: 'doc'
    arethusa:
        :text: 'Arethusa'
        :uri: 'http://github.com/latin-language-toolkit/arethusa'
        :actions:
          :edit:
            :href: "http://localhost/arethusa/app/#/perseidsLANGFORMAT?chunk=SENT"
            :id_param: 'doc'
            :text: "Edit in Arethusa"
          :view:
            :href: "http://localhost/arethusa/app/#/perseidsLANGFORMAT?chunk=SENT&mode=viewer"
            :id_param: 'doc'
            :text: "Preview in Arethusa"
          :create:
            :href: "http://localhost/exist/rest/db/app/treebank-entertext-arethusa-test.xhtml?"
            :id_param: 'doc'
            :text: 'via Arethusa'
  alignment_editor:
    :alpheios:
      :text: 'Alpheios'
      :method: 'get'
      :actions:
        :edit: 
          :href: "http://localhost/exist/rest/db/app/align-editsentence-perseids-test.xhtml?s=SENT&numSentences=MAX"
          :id_param: 'doc'
          :text: "Align in Alpheios"
        :view:
          :href: "http://localhost/exist/rest/db/app/align-editsentence-perseids-test.xhtml?s=SENT&numSentences=MAX&app=viewer"
          :id_param: 'doc'
          :text: "View in Alpheios"
        :create:
          :href: "http://localhost/exist/rest/db/app/align-entersentence-ext.xhtml?"
          :id_param: 'doc'
          :text: 'New Text Alignment'
  oa_editor:
    :perseids:
      :text: 'Annotation Editor'
      :method: 'get'
      :actions:
        :edit:
          :href: "http://localhost/annotation-editor/perseids-annotate.xhtml?&uri=URI&lang=LANG"
          :id_param: 'doc'
          :text: "Edit"
        :view:
          :href: "http://localhost/annotation-editor/perseids-annotate.xhtml?uri=URI&app=viewer&lang=LANG"
          :id_param: 'doc'
  image_service:
    :cite:
      :method: 'get'
      :actions:
        :context:
          :href: "http://services.perseus.tufts.edu/sparqlimg/api?request=GetIIPMooViewer&urn="
        :binary:
          :href:  "http://services.perseus.tufts.edu/sparqlimg/api?request=GetBinaryImage&urn="
  cts_tokenizer:
    :default:
      :method: 'get'
      :actions:
        :tokenize: 
          :href: "http://localhost/exist/rest/db/xq/tokenize.xquery?splitting=false&uri="
    :lat:
      :method: 'get'
      :actions: 
        :tokenize:
          :href: "http://localhost/llt/tokenize?xml=true&merging=false&splitting=false&uri="
  toponym_editor:
    :recogito:
      :method: 'get'
      :text: 'Recogito'
      :target: 'perseids-recogito'
      :actions:
        :export:
          :href: "http://pelagios.org/recogito/edit/annotation?ctsURI="
          :text: "Annotate Toponyms"
        :import:
          :href: "http://pelagios.org/recogito/api/annotations?ctsURI="
          :text: "Import Toponymns"
  review_service:
    TreebankCiteIdentifier:
      :method: 'get'
      :text: 'Compare'
      :target: 'perseids-llt-review'
      :actions:
        :export:
          :href: 'http://74.70.97.104/treebank/diff/html?gold=COMPARE_TO'
          :id_param: 'reviewable'
          :text: 'Compare'
      

    
test:
  treebank_editor:
    alpheios:
      :text: 'Alpheios'
      :method: 'get'
      :uri: 'http://github.com/alpheios-project/treebank-editor'
      :actions:
        :edit:
          :href: "http://localhost/exist/rest/db/app/treebank-editsentence-perseids-test.xhtml?s=SENT&numSentences=MAX"
          :id_param: 'doc'
          :text: 'Edit in Alpheios'
        :view:
          :href: "http://localhost/exist/rest/db/app/treebank-editsentence-perseids-test.xhtml?s=SENT&numSentences=MAX&app=viewer"
          :id_param: 'doc'
          :text: 'Preview in Alpheios'
        :create:
          :href: "http://localhost/exist/rest/db/app/treebank-entertext-perseids-test.xhtml?"
          :id_param: 'doc'
          :text: 'via Alpheios'
    arethusa:
      :text: 'Arethusa'
      :uri: 'http://github.com/latin-language-toolkit/arethusa'
      :actions:
        :edit:
          :href: "http://localhost/arethusa/app/#/perseidsLANGFORMAT?chunk=SENT"
          :id_param: 'doc'
          :text: "Edit in Arethusa"
        :view:
          :href: "http://localhost/arethusa/app/#/perseidsLANGFORMAT?chunk=SENT&mode=viewer"
          :id_param: 'doc'
          :text: "Preview in Arethusa"
        :create:
          :href: "http://localhost/exist/rest/db/app/treebank-entertext-arethusa-test.xhtml?"
          :id_param: 'doc'
          :text: 'via Arethusa'
  alignment_editor:
    :alpheios:
      :text: 'Alpheios'
      :method: 'get'
      :actions:
        :edit: 
          :href: "http://localhost/exist/rest/db/app/align-editsentence-perseids-test.xhtml?s=SENT&numSentences=MAX"
          :id_param: 'doc'
          :text: "Align in Alpheios"
        :view:
          :href: "http://localhost/exist/rest/db/app/align-editsentence-perseids-test.xhtml?s=SENT&numSentences=MAX&app=viewer"
          :id_param: 'doc'
          :text: "View in Alpheios"
        :create:
          :href: "http://localhost/exist/rest/db/app/align-entersentence-ext.xhtml?"
          :id_param: 'doc'
          :text: 'New Text Alignment'
  oa_editor:
    :perseids:
      :text: 'Annotation Editor'
      :method: 'get'
      :actions:
        :edit:
          :href: "http://localhost/annotation-editor/perseids-annotate.xhtml?uri=URI&lang=LANG"
          :id_param: 'doc'
          :text: "Edit"
        :view:
          :href: "http://localhost/annotation-editor/perseids-annotate.xhtml?uri=URI&app=viewer&lang=LANG"
          :id_param: 'doc'
  image_service:
    :cite:
      :method: 'get'
      :actions:
        :context:
          :href: "http://services.perseus.tufts.edu/sparqlimg/api?request=GetIIPMooViewer&urn="
        :binary:
          :href:  "http://services.perseus.tufts.edu/sparqlimg/api?request=GetBinaryImage&urn="
  cts_tokenizer:
    :default:
      :method: 'get'
      :actions:
        :tokenize: 
          :href: "http://localhost/exist/rest/db/xq/tokenize.xquery?splitting=false&uri="
    :lat:
      :method: 'get'
      :actions: 
        :tokenize:
          :href: "http://localhost/llt/tokenize?xml=true&merging=false&splitting=false&uri="
  toponym_editor:
    :recogito:
      :method: 'get'
      :text: 'Recogito'
      :target: 'perseids-recogito'
      :actions:
        :export:
          :href: "http://pelagios.org/recogito/edit/annotation?ctsURI="
          :text: "Annotate Toponyms"
        :import:
          :href: "http://pelagios.org/recogito/api/annotations?ctsURI="
          :text: "Import Toponymns"
    
production:
  treebank_editor:
    alpheios:
      :text: 'Alpheios'
      :method: 'get'
      :uri: 'http://github.com/alpheios-project/treebank-editor'
      :actions:
        :edit:
          :href: "http://sosol.perseids.org/alpheios/app/treebank-editsentence-perseids.xhtml?s=SENT&numSentences=MAX"
          :id_param: 'doc'
          :text: 'Edit in Alpheios'
        :view:
          :href: "http://sosol.perseids.org/alpheios/app/treebank-editsentence-perseids.xhtml?s=SENT&numSentences=MAX&app=viewer"
          :id_param: 'doc'
          :text: 'Preview in Alpheios'
        :create:
          :href: "http://sosol.perseids.org/exist/rest/db/app/treebank-entertext-perseids.xhtml?"
          :text: 'via Alpheios'
    arethusa:
      :text: 'Arethusa'
      :uri: 'http://github.com/latin-language-toolkit/arethusa'
      :actions:
        :edit:
          :href: "http://sosol.perseids.org/tools/arethusa/app/#/perseidsLANGFORMAT?chunk=SENT"
          :id_param: 'doc'
          :text: "Edit in Arethusa"
        :view:
          :href: "http://sosol.perseids.org/tools/arethusa/app/#/perseidsLANGFORMAT?chunk=SENT&mode=viewer"
          :id_param: 'doc'
          :text: "Preview in Arethusa"
        :create:
          :href: "http://sosol.perseids.org/exist/rest/db/app/treebank-entertext-arethusa.xhtml?"
          :id_param: 'doc'
          :text: 'via Arethusa'
  alignment_editor:
    :alpheios:
      :text: 'Alpheios'
      :method: 'get'
      :actions:
        :edit: 
          :href: "http://sosol.perseids.org/alpheios/app/align-editsentence-perseids.xhtml?s=SENT&numSentences=MAX"
          :id_param: 'doc'
          :text: "Align in Alpheios"
        :view:
          :href: "http://sosol.perseids.org/alpheios/app/align-editsentence-perseids.xhtml?s=SENT&numSentences=MAX&app=viewer"
          :id_param: 'doc'
          :text: "View in Alpheios"
        :create:
          :href: "http://sosol.perseids.org/alpheios/app/align-entersentence-perseids.xhtml?"
          :id_param: 'doc'
          :text: 'New Text Alignment'
  oa_editor:
    :perseids:
      :text: 'Annotation Editor'
      :method: 'get'
      :actions:
        :edit:
          :href: "http://sosol.perseids.org/tools/annotation-editor/perseids-annotate.xhtml?uri=URI&lang=LANG"
          :id_param: 'doc'
          :text: "Edit"
        :view:
          :href: "http://sosol.perseids.org/tools/annotation-editor/perseids-annotate.xhtml?uri=URI&app=viewer&lang=LANG"
          :id_param: 'doc'
  image_service:
    :cite:
      :method: 'get'
      :actions:
        :context:
          :href: "http://services.perseus.tufts.edu/sparqlimg/api?request=GetIIPMooViewer&urn="
        :binary:
          :href:  "http://services.perseus.tufts.edu/sparqlimg/api?request=GetBinaryImage&urn="
  cts_tokenizer:
    :default:
      :method: 'get'
      :actions:
        :tokenize: 
          :href: "http://sosol.perseids.org/exist/rest/db/xq/tokenize.xquery?splitting=false&uri="
    :lat:
      :method: 'get'
      :actions: 
        :tokenize:
          :href: "http://services.perseids.org/llt/tokenize?xml=true&merging=false&splitting=false&uri="
  toponym_editor:
    :recogito:
      :method: 'get'
      :text: 'Recogito'
      :target: 'perseids-recogito'
      :actions:
        :export:
          :href: "http://pelagios.org/recogito/edit/annotation?ctsURI="
          :text: "Annotate Toponyms"
        :import:
          :href: "http://pelagios.org/recogito/api/annotations?ctsURI="
          :text: "Import Toponymns"
