development:
  treebank_editor:
    alpheios:
      :text: 'Alpheios'
      :method: 'get'
      :uri: 'http://github.com/alpheios-project/treebank-editor'
      :actions:
        :edit:
          :href: "http://localhost/exist/rest/db/app/treebank-editsentence-perseids-test.xhtml?doc=IDENTIFIER&s=SENT&numSentences=MAX"
          :text: 'Edit in Alpheios'
        :view:
          :href: "http://localhost/exist/rest/db/app/treebank-editsentence-perseids-test.xhtml?doc=IDENTIFIER&s=SENT&numSentences=MAX&app=viewer"
          :text: 'Preview in Alpheios'
        :create:
          :href: "http://localhost/exist/rest/db/app/treebank-entertext-perseids-test.xhtml?doc=IDENTIFIER"
          :text: 'via Alpheios'
    arethusa:
        :target: 'perseids-arethusa'
        :text: 'Arethusa'
        :uri: 'http://github.com/latin-language-toolkit/arethusa'
        :actions:
          :edit:
            :href: "http://localhost/arethusa/app/#/perseidsLANGFORMAT?doc=IDENTIFIER&chunk=SENT"
            :text: "Edit in Arethusa"
          :view:
            :href: "http://localhost/arethusa/app/#/perseidsLANGFORMAT?doc=IDENTIFIER&chunk=SENT&mode=viewer"
            :text: "Preview in Arethusa"
          :create:
            :href: "http://localhost/exist/rest/db/app/treebank-entertext-arethusa-test.xhtml?doc=IDENTIFIER"
            :text: 'via Arethusa'
  alignment_editor:
    :alpheios:
      :text: 'Alpheios'
      :method: 'get'
      :actions:
        :edit: 
          :href: "http://localhost/exist/rest/db/app/align-editsentence-perseids-test.xhtml?doc=IDENTIFIER&s=SENT&numSentences=MAX"
          :text: "Align in Alpheios"
        :view:
          :href: "http://localhost/exist/rest/db/app/align-editsentence-perseids-test.xhtml?doc=IDENTIFIER&s=SENT&numSentences=MAX&app=viewer"
          :text: "View in Alpheios"
  oa_editor:
    :perseids:
      :text: 'Annotation Editor'
      :method: 'get'
      :actions:
        :edit:
          :href: "http://localhost/annotation-editor/perseids-annotate.xhtml?doc=IDENTIFIER&uri=URI"
          :text: "Edit"
        :view:
          :href: "http://localhost/annotation-editor/perseids-annotate.xhtml?doc=IDENTIFIER&uri=URI&app=viewer"
  image_service:
    :cite:
      :method: 'get'
      :actions:
        :context:
          :href: "http://services.perseus.tufts.edu/sparqlimg/api?request=GetIIPMooViewer&urn="
        :binary:
          :href:  "http://services.perseus.tufts.edu/sparqlimg/api?request=GetBinaryImage&urn="
  cts_tokenizer:
    :default:
      :method: 'get'
      :actions:
        :tokenize: 
          :href: "http://localhost/exist/rest/db/xq/tokenize.xquery?splitting=false&uri="
    :lat:
      :method: 'get'
      :actions: 
        :tokenize:
          :href: "http://localhost/llt/tokenize?xml=true&merging=false&splitting=false&uri="
  toponym_editor:
    :recogito:
      :method: 'get'
      :text: 'Recogito'
      :target: 'perseids-recogito'
      :actions:
        :export:
          :href: "http://pelagios.org/recogito/edit/annotation?ctsURI="
          :text: "Annotate Toponyms"
        :import:
          :href: "http://pelagios.org/recogito/api/annotations?ctsURI="
          :text: "Import Toponymns"
    
test:
  treebank_editor:
    alpheios:
      :text: 'Alpheios'
      :method: 'get'
      :uri: 'http://github.com/alpheios-project/treebank-editor'
      :actions:
        :edit:
          :href: "http://localhost/exist/rest/db/app/treebank-editsentence-perseids-test.xhtml?doc=IDENTIFIER&s=SENT&numSentences=MAX"
          :text: 'Edit in Alpheios'
        :view:
          :href: "http://localhost/exist/rest/db/app/treebank-editsentence-perseids-test.xhtml?doc=IDENTIFIER&s=SENT&numSentences=MAX&app=viewer"
          :text: 'Preview in Alpheios'
        :create:
          :href: "http://localhost/exist/rest/db/app/treebank-entertext-perseids-test.xhtml?doc=IDENTIFIER"
          :text: 'via Alpheios'
    arethusa:
        :target: 'perseids-arethusa'
        :text: 'Arethusa'
        :uri: 'http://github.com/latin-language-toolkit/arethusa'
        :actions:
          :edit:
            :href: "http://localhost/arethusa/app/#/perseidsLANGFORMAT?doc=IDENTIFIER&chunk=SENT"
            :text: "Edit in Arethusa"
          :view:
            :href: "http://localhost/arethusa/app/#/perseidsLANGFORMAT?doc=IDENTIFIER&chunk=SENT&mode=viewer"
            :text: "Preview in Arethusa"
          :create:
            :href: "http://localhost/exist/rest/db/app/treebank-entertext-arethusa-test.xhtml?doc=IDENTIFIER"
            :text: 'via Arethusa'
  alignment_editor:
    :alpheios:
      :text: 'Alpheios'
      :method: 'get'
      :actions:
        :edit: 
          :href: "http://localhost/exist/rest/db/app/align-editsentence-perseids-test.xhtml?doc=IDENTIFIER&s=SENT&numSentences=MAX"
          :text: "Align in Alpheios"
        :view:
          :href: "http://localhost/exist/rest/db/app/align-editsentence-perseids-test.xhtml?doc=IDENTIFIER&s=SENT&numSentences=MAX&app=viewer"
          :text: "View in Alpheios"
  oa_editor:
    :perseids:
      :text: 'Annotation Editor'
      :method: 'get'
      :actions:
        :edit:
          :href: "http://localhost/annotation-editor/perseids-annotate.xhtml?doc=IDENTIFIER&uri=URI"
          :text: "Edit"
        :view:
          :href: "http://localhost/annotation-editor/perseids-annotate.xhtml?doc=IDENTIFIER&uri=URI&app=viewer"
  image_service:
    :cite:
      :method: 'get'
      :actions:
        :context:
          :href: "http://services.perseus.tufts.edu/sparqlimg/api?request=GetIIPMooViewer&urn="
        :binary:
          :href:  "http://services.perseus.tufts.edu/sparqlimg/api?request=GetBinaryImage&urn="
  cts_tokenizer:
    :default:
      :method: 'get'
      :actions:
        :tokenize: 
          :href: "http://localhost/exist/rest/db/xq/tokenize.xquery?splitting=false&uri="
    :lat:
      :method: 'get'
      :actions: 
        :tokenize:
          :href: "http://localhost/llt/tokenize?xml=true&merging=false&splitting=false&uri="
  toponym_editor:
    :recogito:
      :method: 'get'
      :text: 'Recogito'
      :target: 'perseids-recogito'
      :actions:
        :export:
          :href: "http://pelagios.org/recogito/edit/annotation?ctsURI="
          :text: "Annotate Toponyms"
        :import:
          :href: "http://pelagios.org/recogito/api/annotations?ctsURI="
          :text: "Import Toponymns"
    
production:
  treebank_editor:
    alpheios:
      :text: 'Alpheios'
      :method: 'get'
      :uri: 'http://github.com/alpheios-project/treebank-editor'
      :actions:
        :edit:
          :href: "http://sosol.perseids.org/alpheios/app/treebank-editsentence-perseids.xhtml?doc=DOC&s=SENT&numSentences=MAX"
          :text: 'Edit in Alpheios'
        :view:
          :href: "http://sosol.perseids.org/alpheios/app/treebank-editsentence-perseids.xhtml?doc=IDENTIFIER&s=SENT&numSentences=MAX&app=viewer"
          :text: 'Preview in Alpheios'
        :create:
          :href: "http://sosol.perseids.org/exist/rest/db/app/treebank-entertext-perseids.xhtml?doc=DOC"
          :text: 'via Alpheios'
    arethusa:
        :target: 'perseids-arethusa'
        :text: 'Arethusa'
        :uri: 'http://github.com/latin-language-toolkit/arethusa'
        :actions:
          :edit:
            :href: "http://sosol.perseids.org/tools/arethusa/app/#/perseidsLANGFORMAT?doc=IDENTIFIER&chunk=SENT"
            :text: "Edit in Arethusa"
          :view:
            :href: "http://sosol.perseids.org/tools/arethusa/app/#/perseidsLANGFORMAT?doc=IDENTIFIER&chunk=SENT&mode=viewer"
            :text: "Preview in Arethusa"
          :create:
            :href: "http://sosol.perseids.org/exist/rest/db/app/treebank-entertext-arethusa.xhtml?doc=IDENTIFIER"
            :text: 'via Arethusa'
  alignment_editor:
    :alpheios:
      :text: 'Alpheios'
      :method: 'get'
      :actions:
        :edit: 
          :href: "http://sosol.perseids.org/alpheios/app/app/align-editsentence-perseids.xhtml?doc=IDENTIFIER&s=SENT&numSentences=MAX"
          :text: "Align in Alpheios"
        :view:
          :href: "http://sosol.perseids.org/alpheios/app/align-editsentence-perseids.xhtml?doc=IDENTIFIER&s=SENT&numSentences=MAX&app=viewer"
          :text: "View in Alpheios"
  oa_editor:
    :perseids:
      :text: 'Annotation Editor'
      :method: 'get'
      :actions:
        :edit:
          :href: "http://sosol.perseids.org/tools/annotation-editor/perseids-annotate.xhtml?doc=IDENTIFIER&uri=URI"
          :text: "Edit"
        :view:
          :href: "http://sosol.perseids.org/tools/annotation-editor/perseids-annotate.xhtml?doc=IDENTIFIER&uri=URI&app=viewer"
  image_service:
    :cite:
      :method: 'get'
      :actions:
        :context:
          :href: "http://services.perseus.tufts.edu/sparqlimg/api?request=GetIIPMooViewer&urn="
        :binary:
          :href:  "http://services.perseus.tufts.edu/sparqlimg/api?request=GetBinaryImage&urn="
  cts_tokenizer:
    :default:
      :method: 'get'
      :actions:
        :tokenize: 
          :href: "http://sosol.perseids.org/exist/rest/db/xq/tokenize.xquery?splitting=false&uri="
    :lat:
      :method: 'get'
      :actions: 
        :tokenize:
          :href: "http://services.perseids.org/llt/tokenize?xml=true&merging=false&splitting=false&uri="
  toponym_editor:
    :recogito:
      :method: 'get'
      :text: 'Recogito'
      :target: 'perseids-recogito'
      :actions:
        :export:
          :href: "http://pelagios.org/recogito/edit/annotation?ctsURI="
          :text: "Annotate Toponyms"
        :import:
          :href: "http://pelagios.org/recogito/api/annotations?ctsURI="
          :text: "Import Toponymns"